networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/ect/nginx/nginx.conf'
    depends_on:
      - webapp
      - client
    networks:
      - dev
  client:
    build:
      context: ./client


  webapp:
    build:
      context: ./webapp
    networks:
      - dev