# docker-compose -f docker-compose.dev.yml build
# docker-compose -f docker-compose.dev.yml up -d
networks:
  dev:

services:
  client:
    build:
      context: ./client/francisco
    container_name: react
    networks:
      - dev

  webapp:
    build: ./webapp
    container_name: fastapi
    command: uvicorn --host 0.0.0.0 --port 8000 main:app # pip
    environment:
      - DATABASE_URL=postgresql://francisco:francisco@db:5432/francisco # путь до бд, см. db service
    volumes:
      - ./webapp:/webapp
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - dev


  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=francisco
      - POSTGRES_PASSWORD=francisco_psw
      - POSTGRES_DB=francisco_db
    networks:
      - dev


  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@francisco.ru
      - PGADMIN_DEFAULT_PASSWORD=francisco # если сменить здесь, то нужно удалить контентер
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0 # чтобы не было косяков с nginx лушче в одну сеть с app
      - PGADMIN_LISTEN_PORT=5555
    networks:
      - dev


  nginx:
    build: ./nginx
    ports:
      - 443:443
    volumes:
      - ./client/francisco/build:/home/web/default/static
      - ./nginx/nginx.conf:/etс/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - client
      - webapp
      - pgadmin
    networks:
      - dev